apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web2
      image: httpd
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
